# Site Settings
locale                   : "en"
title                    : "Sparrow"
title_separator          : "-"
description              : "A clean, minimalistic, and fully responsive Jekyll theme"
favicon                  : "/assets/images/bird.png"
avatar                   : "/assets/images/bird.png"

url                      : "https://theconfused.me/" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/sparrow" # the subpath of your site, e.g. "/blog"
repository               : "lingxz/sparrow" # GitHub username/repo-name e.g. "lingxz/sparrow"

# Site Author
author:
  name                   : "Lingyi" # appears in the footer and atom feed

comments                 : true
disqus:
  shortname              : sparrow-theme # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


og_image                 : "/assets/images/bird.png" # Open Graph/Twitter default site image
github:
  username               : "lingxz"


# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-96137027-1"

# Reading Files
include:
  - _pages
# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock

encoding: "utf-8"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /blog/:title/
paginate: 8 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections:
  poetry:
    output: true
    permalink: /:collection/:title/

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: true
      comments: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
      comments: true
      share: true
  # _poetry
  - scope:
      path: ""
      type: poetry
    values:
      layout: post
      author_profile: true
      share: false